import type { CodeTok } from '@www/shared/components/media/CodeSample';

/** Mini dashboard: composed Row, multiple widgets, click reaction, served in-browser. */
export const UI_COUNTER_LINES: CodeTok[][] = [
  [{ c: 'kw', t: 'import' }, { t: ' nu' }],
  [{ c: 'kw', t: 'import' }, { t: ' nustd' }],
  [],
  [{ c: 'kw', t: 'class' }, { t: ' StatsRow(' }, { c: 'nu', t: 'nustd.ui.Row' }, { t: '):' }],
  [{ t: '    users = ' }, { c: 'nu', t: 'nustd.ui.StatRef' }, { t: '.slot()' }],
  [{ t: '    online = ' }, { c: 'nu', t: 'nustd.ui.StatRef' }, { t: '.slot()' }],
  [{ t: '    health = ' }, { c: 'nu', t: 'nustd.ui.BadgeRef' }, { t: '.slot()' }],
  [],
  [{ c: 'kw', t: 'class' }, { t: ' Dashboard(' }, { c: 'nu', t: 'nustd.ui.Page' }, { t: '):' }],
  [{ t: '    stats = StatsRow.slot()' }],
  [{ t: '    table = ' }, { c: 'nu', t: 'nustd.ui.TableRef' }, { t: '.slot(columns=[' }, { c: 'str', t: '"user"' }, { t: ', ' }, { c: 'str', t: '"last seen"' }, { t: '])' }],
  [{ t: '    refresh = ' }, { c: 'nu', t: 'nustd.ui.ButtonRef' }, { t: '.slot(label=' }, { c: 'str', t: '"Refresh"' }, { t: ')' }],
  [],
  [{ c: 'kw', t: 'class' }, { t: ' App(' }, { c: 'nu', t: 'nustd.ui.Index' }, { t: '):' }],
  [{ t: '    pages = ' }, { c: 'nu', t: 'nustd.ui.Pages' }, { t: '({' }, { c: 'str', t: '"/"' }, { t: ': Dashboard})' }],
  [],
  [{ c: 'cmt', t: '# writes from python go straight to the browser' }],
  [{ t: 'paint = (' }],
  [{ t: '    Dashboard.stats.users.set_value(' }, { c: 'str', t: '"142"' }, { t: ')' }],
  [{ t: '    | Dashboard.stats.online.set_value(' }, { c: 'str', t: '"38"' }, { t: ')' }],
  [{ t: '    | Dashboard.stats.health.set(label=' }, { c: 'str', t: '"healthy"' }, { t: ', variant=' }, { c: 'str', t: '"ok"' }, { t: ')' }],
  [{ t: '    | Dashboard.table.set(rows=[[' }, { c: 'str', t: '"ada"' }, { t: ', ' }, { c: 'str', t: '"2m ago"' }, { t: '], [' }, { c: 'str', t: '"bob"' }, { t: ', ' }, { c: 'str', t: '"just now"' }, { t: ']])' }],
  [{ t: ')' }],
  [],
  [{ c: 'cmt', t: '# clicks come back into the same ref' }],
  [{ t: 'on_refresh = ' }, { c: 'nu', t: 'nu.ReactForever' }, { t: '(Dashboard.refresh.clicked(), paint)' }],
  [],
  [{ c: 'cmt', t: '# serve it' }],
  [{ t: 'app = ' }, { c: 'nu', t: 'nu.With' }, { t: '(' }, { c: 'nu', t: 'nustd.ui.server' }, { t: '(paint >> on_refresh), body=' }, { c: 'nu', t: 'nu.ForeverDo' }, { t: '(' }, { c: 'nu', t: 'nu.Delay' }, { t: '(' }, { c: 'num', t: '3600' }, { t: ')))' }],
  [{ c: 'nu', t: 'nu.run' }, { t: '(app)' }],
];
